version: '3.7'

services:
  db_sharing:
    image: mysql:8.0
    volumes:
      - ./docker/data/db/:/var/lib/mysql
    ports:
      - "3800:3306"
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  sharing:
    user: "1000:1000"
    depends_on:
      - db_sharing
    build:
      context: .
      dockerfile: app.Dockerfile
    volumes:
      - .:/var/www/html/:consistent
    networks:
      - default
    environment:
      XDEBUG_MODE: "off"                 # disable xdebug unless debugging
  web_sharing:
    image: nginx:latest
    volumes:
      - .:/var/www/html:ro
      - ./docker/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9300:80"
    depends_on:
      - sharing

volumes:
  vendor:
  node_modules: