version: '3.7'

services:
  db_sharing:
    image: mysql:8.0
    volumes:
      - ./docker/data/db/:/var/lib/mysql
    ports:
      - "3800:3306"
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  sharing:
    depends_on:
      - db_sharing
      - redis
    build:
      context: .
      dockerfile: app.Dockerfile
    volumes:
      - .:/var/www/html/:consistent
      - ./.gnupg:/root/.gnupg
    networks:
      - default
    environment:
      XDEBUG_MODE: "coverage"
      BROADCAST_CONNECTION: reverb
      REVERB_HOST: reverb
      REVERB_PORT: 8080
      REVERB_SCHEME: http
      GNUPGHOME: /root/.gnupg
      GPG_TTY: "/dev/tty"
  reverb:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: app.Dockerfile
    working_dir: /var/www/html
    command: php artisan reverb:start --no-interaction --host=0.0.0.0 --port=8080
    volumes:
      - .:/var/www/html/
    expose:
      - "8080"
  web_sharing:
    image: nginx:latest
    volumes:
      - .:/var/www/html:ro
      - ./docker/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9300:80"
    depends_on:
      - sharing
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
volumes:
  vendor:
  node_modules: