exclude_patterns = [
  "**/vendor/**",
  "**/dist/**",
  "**/node_modules/**",
  "**/cache/**",
  ""***/public/**"
]

test_patterns = ["**/tests/**"]

[project]
name = "WP-XPub"
language = "php"
coverage = true

[coverage]
report = "coverage/clover.xml"
tool = "phpunit"

[analyze]
enabled = true

[similar_code]
exclude_patterns = [
  "**/tests/**",
  "**/dist/**",
  "**/vendor/**",
  "**/docs/**"
]

[files]
include = ["src/"]
exclude = [
  "vendor/**",
  "tests/**",
  "dist/**",
  "node_modules/**",
  "public/**"
]
