exclude_patterns = [
  "**/vendor/**",
  "**/dist/**",
  "**/node_modules/**",
  "**/cache/**",
  "**/public/**",
  "**/app/Policies/**",
  "**/database/**",
  "**/lang/**",
  "**/deploy_laravel_config.php"
]

test_patterns = ["**/tests/**"]

[project]
name = "dashclip-delivery"
language = "php"
coverage = true

[coverage]
report = "coverage/clover.xml"
tool = "phpunit"

[analyze]
enabled = true

[similar_code]
exclude_patterns = [
  "**/tests/**",
  "**/dist/**",
  "**/vendor/**",
  "**/docs/**",
  "**/public/**",
  "**/database/**",
  "**/lang/**",
  "**/deploy_laravel_config.php"
]

[files]
include = ["app/"]
exclude = [
  "vendor/**",
  "tests/**",
  "dist/**",
  "node_modules/**",
  "public/**",
  "app/Policies/**",
  "**/database/**",
  "**/lang/**",
  "**/deploy_laravel_config.php"
]
