<?php

declare(strict_types=1);

namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Mail\Mailable;
use Illuminate\Mail\Mailables\Content;
use Illuminate\Mail\Mailables\Envelope;
use Illuminate\Queue\SerializesModels;

abstract class AbstractLoggedMail extends Mailable implements ShouldQueue
{
    use Queueable, SerializesModels;

    protected string $subjectLine = '';

    abstract protected function viewName(): string;

    protected function viewData(): array
    {
        return [];
    }

    public function subject($subject)
    {
        return parent::subject($subject); // TODO: Change the autogenerated stub
    }

    public function envelope(): Envelope
    {
        return new Envelope(
            subject: $this->subjectLine,
        );
    }

    public function content(): Content
    {
        return new Content(
            view: $this->viewName(),
            with: array_merge($this->viewData(), [
                'subject' => $this->subjectLine,
            ]),
        );
    }

    public function headers(): Headers
    {
        return new Headers(
            messageId: $this->generate,
            text: [
                // RFC 3834-konform (Auto-Reply)
                'Auto-Submitted' => 'auto-replied',
                // verhindert Schleifen, v. a. bei Outlook / Exchange
                'X-Auto-Response-Suppress' => 'All',
            ],
        );
    }

}